name: Deploy to VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set permissions for SSH key
        run: chmod 600 $HOME/.ssh/id_rsa

      - name: SSH into VM and deploy
        run: |
          ssh ubuntu@172.31.26.176 \
            'cd /home/ubuntu/python-fastapi-demo-docker &&
            git pull &&
            docker-compose down &&
            docker-compose up -d --build'
