name: Deploy to VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: appleboy/ssh-action@v1.0.3
        
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami

      - name: SSH into VM and deploy
        run: |
          ssh ubuntu@172.31.26.176 \
            'cd /home/ubuntu/python-fastapi-demo-docker &&
            git pull &&
            docker-compose down &&
            docker-compose up -d --build'
