name: Deploy to VM while pushing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into VM and deploy
        run: |
          ssh -v ubuntu@35.154.116.211 \
            'cd /home/ubuntu/python-fastapi-demo-docker &&
            git pull &&
            docker compose down &&
            docker compose up -d --build'
